# Generated by Django 3.2 on 2022-01-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cook_time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='prep_time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='total_time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_length',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='preparation_length',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_length',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
